### ISSUE TITLE
Implement profiler.node.excludeurl

### ISSUE THREAD

**Issue by davide-parini** [pinpoint-apm/pinpoint-node-agent#1]
Hello, is there any way to exclude some urls from profiling, in the same way it can be done for instance with profiler.tomcat.excludeurl on the Java agent?

If not, do you plan to implement such a feature in the near future?

Thank you very much for your work

**Comment by feelform** [comment]
@davide-parini 
right. I have a plan for excludeURL. 

Thank you for your Node agent interesting.

**Comment by feelform** [comment]
Hello @davide-parini 

I have published Node agent 0.7.1 with exclusion URLs. You can config a PINPOINT_TRACE_EXCLUSION_URL_PATTERN Environment in https://github.com/pinpoint-apm/pinpoint-node-agent/blob/master/README.md#environment-variables

Thanks

**Comment by davide-parini** [comment]
Thank you very much @feelform!
