### ISSUE TITLE
not working on PM2 (not working properly detect outgoing request)

### ISSUE THREAD

**Issue by uyu423** [pinpoint-apm/pinpoint-node-agent#11]
Hi there.

There is a problem that outgoing requests are not properly detected when the process is run as pm2.
It seems that outgoing request hooking does not work in pm2 environment.
I tried to find the problem myself, but failed to determine the cause.

To check the problem, I modified the code below to run the debug console.

### [lib/instrumentation/http-shared.js#L65](https://github.com/pinpoint-apm/pinpoint-node-agent/blob/d14e5a52f6dbb14d2bd42697aff47be3a0dcebc9/lib/instrumentation/http-shared.js#L65)
```js
      log.debug('start traceOutgoingRequest')
      const req = original.apply(this, arguments)
      const trace = agent.traceContext.currentTraceObject()
      log.debug('trace', trace)  // added code

      if (!trace) return req

      if (!trace.canSampled()) {
        RequestHeaderUtils.writeHTTPSampled(req)
        return req
      }
```

### [lib/context/context-manager.js#L14](https://github.com/pinpoint-apm/pinpoint-node-agent/blob/d14e5a52f6dbb14d2bd42697aff47be3a0dcebc9/lib/context/context-manager.js#L14)
```js
const init = (asyncId, type, triggerAsyncId, resource) => {
  if (type === 'TIMERWRAP') return
  if (traceObjectMap.has(triggerAsyncId)) {
    log.debug(triggerAsyncId, 'set OK') // added code
    traceObjectMap.set(asyncId, traceObjectMap.get(triggerAsyncId))
  } else {
    log.debug(triggerAsyncId, 'set NOT OK') // added code
  }
}
```

And there was a difference between the node process running the vanilla `node` command and the node process running using `pm2`.

In the `pm2` execution environment, `trace`(`agent.traceContext.currentTraceObject()`) is undefined even if outgoing request is detected. and all `traceObjectMap.set` judgments (`contextManager.init()`) are false.

### Process execution result with `pm2` command
```
trace undefined # << trace is undefined
1673 set NOT OK
1674 set NOT OK
1675 set NOT OK
1676 set NOT OK
// ...
// everything is NOT OK
// ...
1808 set NOT OK
1809 set NOT OK
sendStats pStatMessage: {"agentId":"i-03bb7c559654ce686_f1ee","agentStartTime":1604034700967,"timestamp":1604034726991,"collectInterval":1000,"memory":{"heapUsed":105577776,"heapTotal":113004544},"cpu":{"user":0.19677778390364023,"system":0},"activeTrace":{"schema":{"typeCode":2,"fast":1000,"normal":3000,"slow":5000},"typeCode":2,"fastCount":0,"normalCount":0,"slowCount":0,"verySlowCount":0}}
1810 set NOT OK
1811 set NOT OK
send full stats at1604034726991
```

But, process executed by the `node` command seems to work correctly.

### Process execution result with `node` command
```
trace Trace {
  traceId: TraceId {
    transactionId: TransactionId {
      agentId: 'i-03bb7c559654ce686_cd24',
      agentStartTime: '1604034795756',
      sequence: '0'
    },
    spanId: '7560621802209459',
    parentSpanId: '-1',
    flag: 0
  },
  agentInfo: {
    agentId: 'i-03bb7c559654ce686_cd24',
    applicationName: 'test-dev',
    agentStartTime: 1604034795756,
    serviceType: 1400
  },
 // ... skip
  storage: BufferedStorage {
    dataSender: DataSender {
      enabledDataSending: true,
      dataSender: [GrpcDataSender]
    },
    createSpanChunk: [Function],
    bufferSize: 10,
    storage: [ [SpanEvent] ]
  },
  callStack: [],
  sequence: 1,
  sampling: true
}
{
  getObject: [Function: getObject],
  setObject: [Function: setObject],
  getAllObject: [Function: getAllObject],
  start: [Function: start]
}
>> GETTER ASYNC ID: 1609
>> MAP LENGTH: undefined
>> Writer http header
 [Object: null prototype] {
  'user-agent': 'axios/0.18.1',
  host: 'test.test.in',
  'pinpoint-traceid': 'i-03bb7c559654ce686_cd24^1604034795756^0',
  'pinpoint-spanid': 7506321793742509,
  'pinpoint-pspanid': '7560621802209459',
  'pinpoint-pappname': 'test',
  'pinpoint-papptype': 1400,
  'pinpoint-flags': 0,
  'pinpoint-host': 'test.test.in'
}
1621 set OK
1622 set OK
1623 set OK
1624 set OK
1625 set OK
1626 set OK
1627 set OK
1628 set OK
1629 set OK
1630 set OK
1631 set OK
intercepted http.ClientcRequest response event { id: '*.com/members//list' }
1632 set OK
1633 set OK
1634 set OK
1635 set OK
intercepted http.IncomingMessage end event { id: 'test.test.in/members/1/list' }
1636 set OK
sendSpanChunk pSpanChunk: {"spanchunk":{"version":1,"transactionid":{"agentid":"i-03bb7c559654ce686_cd24","agentstarttime":"1604034795756","sequence":"0"},"spanid":"7560621802209459","endpoint":"","spaneventList":[{"sequence":0,"depth":1,"startelapsed":0,"endelapsed":0,"servicetype":100,"annotationList":[],"apiid":2,"exceptioninfo":null,"nextevent":{"messageevent":{"nextspanid":-1,"endpoint":"","destinationid":""}},"asyncevent":0},{"sequence":1,"depth":2,"startelapsed":0,"endelapsed":0,"servicetype":9056,"annotationList":[{"key":12,"value":{"stringvalue":"GET","boolvalue":false,"intvalue":0,"longvalue":0,"shortvalue":0,"doublevalue":0,"binaryvalue":"","bytevalue":0}},{"key":40,"value":{"stringvalue":"test.test.in/members/1/list","boolvalue":false,"intvalue":0,"longvalue":0,"shortvalue":0,"doublevalue":0,"binaryvalue":"","bytevalue":0}},{"key":46,"value":{"stringvalue":"","boolvalue":false,"intvalue":200,"longvalue":0,"shortvalue":0,"doublevalue":0,"binaryvalue":"","bytevalue":0}}],"apiid":0,"exceptioninfo":null,"nextevent":{"messageevent":{"nextspanid":7506321793742509,"endpoint":"localhost:7777","destinationid":"test.test.in"}},"asyncevent":0}],"applicationservicetype":1400,"keytime":1604034799385,"localasyncid":{"asyncid":2,"sequence":0}}}
1637 set OK
1638 set OK
1639 set OK
// ... everything set OK
1675 set OK
1676 set OK
1677 set OK
sendSpan pSpan: {"span":{"version":1,"transactionid":{"agentid":"i-03bb7c559654ce686_cd24","agentstarttime":"1604034795756","sequence":"0"},"spanid":"7560621802209459","parentspanid":"-1","starttime":1604034799292,"elapsed":193,"apiid":1,"servicetype":1400,"acceptevent":{"rpc":"/v6-6/event/calendar_2020/hit","endpoint":"localhost:7777","remoteaddr":"127.0.0.1","parentinfo":{"parentapplicationname":"","parentapplicationtype":0,"acceptorhost":""}},"annotationList":[{"key":46,"value":{"stringvalue":"","boolvalue":false,"intvalue":200,"longvalue":0,"shortvalue":0,"doublevalue":0,"binaryvalue":"","bytevalue":0}}],"flag":0,"err":0,"spaneventList":[{"sequence":0,"depth":1,"startelapsed":50,"endelapsed":0,"servicetype":9057,"annotationList":[{"key":12,"value":{"stringvalue":"http.request","boolvalue":false,"intvalue":0,"longvalue":0,"shortvalue":0,"doublevalue":0,"binaryvalue":"","bytevalue":0}}],"apiid":0,"exceptioninfo":null,"nextevent":{"messageevent":{"nextspanid":-1,"endpoint":"localhost:7777","destinationid":"localhost:7777"}},"asyncevent":1},{"sequence":1,"depth":1,"startelapsed":42,"endelapsed":0,"servicetype":9057,"annotationList":[{"key":12,"value":{"stringvalue":"http.request","boolvalue":false,"intvalue":0,"longvalue":0,"shortvalue":0,"doublevalue":0,"binaryvalue":"","bytevalue":0}}],"apiid":0,"exceptioninfo":null,"nextevent":{"messageevent":{"nextspanid":-1,"endpoint":"localhost:7777","destinationid":"localhost:7777"}},"asyncevent":2}],"exceptioninfo":null,"applicationservicetype":1400,"loggingtransactioninfo":0}}
1678 set OK
// ... everything set OK
1700 set OK
1701 set NOT OK
1702 set NOT OK
1703 set OK
1704 set OK
```

I don't know where to check to see this problem. can I check another?

please feedback. Thank you.

**Comment by feelform** [comment]
@uyu423 
```
pinpoint-node-agent/demo/express on  master [!] via 🤖 v12.18.2 
❯ node -v
v12.18.2

pinpoint-node-agent/demo/express on  master [!] via 🤖 v12.18.2 
❯ pm2 -v
4.2.3
```

I checked pm2 with Pinpoint Node agent. I can checked outgoing request.
<img width="260" alt="Screen Shot 2020-10-30 at 6 07 58 PM" src="https://user-images.githubusercontent.com/616895/97680982-e5786f00-1ada-11eb-9cea-f44c521b35fd.png">

**Comment by uyu423** [comment]
@feelform  OK. I will test a little more in our condition. Still in our project, the `pinpoint-node-agent` and `pm2` combination cannot properly collect outgoing requests. There seems to be some special condition.

**Comment by feelform** [comment]
@uyu423 

Could you share your environments ? Do you use 0.7.0-rc.0?

Thank you for your questions.

**Comment by uyu423** [comment]
@feelform

In this regard, I did an additional test.
Please refer to my GitHub repository (https://github.com/uyu423/pinpoint-node-agent-pm2-test, Korean)

There seems to be a problem with the combination with request libraries like `axios`, not `pm2`.
It's not the same as the problem I'm experiencing, but the situation of not collecting outgoing requests is the same.

I'm still working fine with `node` runtime, and having problems with `pm2-runtime` runtime. 
However, the status is similar, so it would be nice if it helps to identify the problem.

Thank you.

**Comment by feelform** [comment]
@uyu423 
Thank you for your a pm2 issue repository. I will check it too.

**Comment by feelform** [comment]
@uyu423 
Before testing, I looked at your detailed readme. When the start traceOutgoingRequest is printed, it means that the hook is successful. 

I looked at the .env_sample file. Did you use the sampling rate as the default (10) when testing? 

If you have used the default sampling rate, please select the desired result value.

**Comment by feelform** [comment]
@uyu423 

I checked your pm2 sample app. first. Thank you.
```
sendStats pStatMessage: {"agentId":"axios","agentStartTime":1604384851972,"timestamp":1604385173136,"collectInterval":1000,"memory":{"heapUsed":19006152,"heapTotal":21700608},"cpu":{"user":0.0180388465978816,"system":0},"activeTrace":{"schema":{"typeCode":2,"fast":1000,"normal":3000,"slow":5000},"typeCode":2,"fastCount":0,"normalCount":0,"slowCount":0,"verySlowCount":1}}
send full stats at1604385173136
intercepted request event call to http.Server.prototype.emit
start instrumentRequest
>> Read DATA from http header 
 RequestData {
  transactionId: null,
  spanId: null,
  parentSpanId: null,
  parentApplicationName: null,
  parentApplicationType: null,
  flags: null,
  host: null,
  sampled: null,
  isRoot: true,
  rpcName: '/',
  endPoint: 'localhost:3000',
  remoteAddress: '::1'
}
```

I have verified that pinpoint related headers are written and sent in your test app.

I looked at your detailed readme. I looked at the .env_sample file. Did you use the sampling rate as the default (10) when testing? 

If you have used the default sampling rate, please select the desired result value.

If you haven't used the default sampling rate, please share. I'll retry to test.

**Comment by uyu423** [comment]
@feelform
I would have used the PINPOINT_SAMPLING_RATE because nothing changed other than the key value contained in `.env_sample`.
When you test, does my test app collect the second outgoing request well?

**Comment by feelform** [comment]
@uyu423 
It is collected according to the set sampling rate.

Have you tested with version 0.7.0-rc.0?

**Comment by uyu423** [comment]
@feelform 

> I would have used the PINPOINT_SAMPLING_RATE.

I missing a word in the middle. I would have used the "default" PINPOINT_SAMPLING_RATE.

---

I tested it on 0.7.0-rc.0 as in the package.json of the test app. [package.json:43](https://github.com/uyu423/pinpoint-node-agent-pm2-test/blob/main/package.json#L43)

**Comment by feelform** [comment]
@uyu423 
It is not necessary to set SMAPLING_RATE. The Node agent creates a span according to the sampling rate. The default sampling rate(10) creates a span by 10 requests.

Thank you

**Comment by uyu423** [comment]
@feelform 
I understand the sampling rate. Then my test app didn't have any problems.
Now in my project I only need to check why outgoing request is not sampled in pm2-runtime environment. This will be created as a separate issue after testing.

Thank you.

**Comment by feelform** [comment]
@uyu423 
You should post issues the test with the Pinpoint Node agent.

**Comment by uyu423** [comment]
@feelform 

> You should post issues the test with the Pinpoint Node agent.

What does this mean? I ran all tests with the Pinpoint Node Agent.

**Comment by feelform** [comment]
@uyu423 
I ran your test app and can't find outgoing issues, so I checked the values of your preferences. But i don't know why your test is failure.
