### ISSUE TITLE
nest.js https 500 status display as normal(green)

### ISSUE THREAD

**Issue by bigtechsolution** [pinpoint-apm/pinpoint-node-agent#127]
I am currently monitoring the backend of nest.js using node-agent on Kubernetes with pinpoint. 

When there is an HTTP status 500 error in nest.js, it is not displayed as an error in pinpoint web, but rather as normal (green). 
It does not work properly when I add the env PINPOINT_HTTP_STATUS_CODE_ERRORS like other environment variables.

It's not clear from the information given whether the issue is caused by nest.js or node-agent. 
and .. It's also possible that there is a problem with the way the HTTP status codes are being handled by pinpoint.

Are there any others experiencing the same issue as me?

**Comment by feelform** [comment]
Hello, @bigtechsolution 
Pinpoint Node agent doesn't support  the nest.js module. It needs different monitoring features. so We will support nest.js modules this year.

Thanks

**Comment by bigtechsolution** [comment]
thanks for reply
