### ISSUE TITLE
Server Error in node-agent while loading application.

### ISSUE THREAD

**Issue by 26goyalaryan** [pinpoint-apm/pinpoint-node-agent#130]
After running the application on 8080 port.

![server-error](https://user-images.githubusercontent.com/71383064/224630777-f491e47e-874c-450b-a9bd-89492a10f077.JPG)

What is the solution to this ?

**Comment by 26goyalaryan** [comment]
@feelform also, In the application list, it is not showing my application even after following the steps mentioned in the documentation.

**Comment by feelform** [comment]
Hello, @26goyalaryan 

It is the Pinpoint Node.js agent repository. Could you ask an your question to https://github.com/pinpoint-apm/pinpoint/issues ?

Thanks
