### ISSUE TITLE
Pinpoint web is showing duplicate nodes for same application

### ISSUE THREAD

**Issue by ravi-kumar-yadav** [pinpoint-apm/pinpoint-node-agent#131]
We are using pinpoint for Nodejs project, and it's showing duplicate nodes/instances in web view for same project.

Our Nodejs application is running on port: 6789, In Pinpoint-web I could see two impressions (nodes) for same application. One of the impression is shown as Nodejs app (name: remote-app1) and another one (duplicate impression i.e. localhost:6789) is shown as Redis (Note: we aren't using Redis in our whole project at all).

![image](https://user-images.githubusercontent.com/11976090/229978975-8805a6bc-e143-4e10-a645-1c771d806983.png)

**Comment by feelform** [comment]
@ravi-kumar-yadav 
Could you share your Inspector of node.js servers ?
