### ISSUE TITLE
node Agent support next.js?

### ISSUE THREAD

**Issue by heejongkim2** [pinpoint-apm/pinpoint-node-agent#138]
hello 

I've completed the Node agent setup for Next.js, but while resource usage is showing up, request data is not being traced

node version : 18.x.x
next.js version : 12.3.1
agent version : 0.8.0 / 0.8.1 / 0.8.2 / 0.9.0-next.0 

<img width="1489" alt="스크린샷 2023-08-30 오후 11 56 41" src="https://github.com/pinpoint-apm/pinpoint-node-agent/assets/43771624/5e5ff678-0781-4762-b36d-f15e8f271959">
<img width="1271" alt="스크린샷 2023-08-30 오후 11 54 37" src="https://github.com/pinpoint-apm/pinpoint-node-agent/assets/43771624/6ad7b973-102f-4961-a3c1-1579572b802e">

Pinpoint Agent Debug log
[Pinpoint Agent][testagentID] Init Started
sendAgentInfo pAgentInfo: {"hostname":"M1.local","ip":"172.30.1.90","ports":"","servicetype":1400,"pid":20409,"agentversion":"0.9.0-next.0","vmversion":"","endtimestamp":0,"endstatus":0,"container":false}
The scheduler is scheduled to run every 86400000ms
sendApiMetaInfo pApiMetaData: {"apiid":1,"apiinfo":"Node Server Process","line":-1,"type":100}
sendApiMetaInfo pApiMetaData: {"apiid":2,"apiinfo":"Asynchronous Invocation","line":-1,"type":200}
The scheduler is scheduled to run every 5000ms
The scheduler is scheduled to run every 300000ms
sendPing pPing: {"wrappers_":null,"arrayIndexOffset_":-1,"array":[],"pivot_":1.7976931348623157e+308,"convertedPrimitiveFields_":{}}
[Pinpoint Agent][testagentID] Init Completed
GrpcBidirectionalStream stream data. pingStream on(data):
sendStats pStatMessage: {"agentId":"testagentID","agentStartTime":1693406513102,"timestamp":1693406519125,"collectInterval":1000,"memory":{"heapUsed":164954176,"heapTotal":215793664},"cpu":{"user":0.004979481533805039,"system":0},"activeTrace":{"schema":{"typeCode":2,"fast":1000,"normal":3000,"slow":5000},"typeCode":2,"fastCount":0,"normalCount":0,"slowCount":0,"verySlowCount":0}}
send full stats at1693406519125

I added  -r pinpoint-agent option like blow

      script: 'node_modules/next/dist/bin/next',
      node_args: ['-r', 'pinpoint-node-agent'],
      args: 'start',

**Comment by feelform** [comment]
Did you test pinpoint-node-agent with PM2 v5.x? It is right. You can use below PM2 ecosystem file.
```
"io": {
   "conf": {
         "metrics": {
              "http": false
          }
    }
}
```

**Comment by heejongkim2** [comment]
thank you. Problem solved.
