### ISSUE TITLE
user resources not being tracked  in next.js issue, and solution

### ISSUE THREAD

**Issue by kis0421** [pinpoint-apm/pinpoint-node-agent#141]
hi, 
It's the similar issues (https://github.com/pinpoint-apm/pinpoint-node-agent/issues/138)

node: v14.18.x
next: v.12.3.1
agent version: 0.8.x / 0.9.x

Heap usage and cpu usage are tracked.
but, apdex and resource usage are not collected.

then, while looking at the github source, I discovered syntax error

**lib/instrumentation/module/mysql2.js**
https://github.com/pinpoint-apm/pinpoint-node-agent/commit/54ace1e5bf4264056cd43adbdb75202c99583d2b#diff-9f4c1711deebfcf0e312a7fdac486c2d6bc6bba2ada24a15864dbd0901906d9bR107

surprisingly, all versions currently registered on npm are missing syntax.
there are no parentheses in mysql2.js in node_modules/pinpoint-node-agent installed via npm i
so I did a custom job adding the missing parentheses via patch-package.
as a result, resource tracking is currently being collected normally.

1. **npm install -d patch-package**
2.  Add **"postinstall": "patch-package"** to package.json script
3.  Add missing parentheses  **}** to **mysql2.js** within node_modules/pinpoint-node-agent
4.  **npx patch-package pinpoint-node-agent**

In the master branch, the missing parentheses in mysql2.js are fixed, but they are excluded in the published version.
When will the next version that fixes the missing parentheses be released?

thanks.

**Comment by kis0421** [comment]
next.js + webpack environment,
It is assumed that there is a difference in the way the core module and the file module operate.
Since it is not related to the above, I will close the issue.

**Comment by heejongkim2** [comment]
thank you.Problem solved.
