### ISSUE TITLE
Suggest 'PINPOINT_UNSTABLE_ID_MAX_LEN' option to env

### ISSUE THREAD

**Issue by nonoll** [pinpoint-apm/pinpoint-node-agent#179]
> I'm not good at English.
It was written using a translator.

## Is your feature request related to a problem? Please describe.
- 'PINPOINT_AGENT_ID' and 'PINPOINT_APPY_NAME' are guided by a 24-character limit in README.
- However, it seems that the restrictions may vary depending on where you actually install and operate

## Describe alternatives you've considered
- Add the value 'PINPOINT_UNSTABLE_ID_MAX_LEN' to .env and utilize it in config.js.
- It also outputs a warning log so that the user can recognize it

```js
// /lib/config.js

const ENV_MAP = {
  // ...
  unstableIdMaxLen: valueOfNumber('PINPOINT_UNSTABLE_ID_MAX_LEN'),
}

// ...

const configurationValueValidations = {
  // ...
  validateIds: () => {
    [{ id: agentConfig.agentId, name: 'Agent ID' }, { id: agentConfig.applicationName, name: 'Application Name' }].filter(id => id.id)
      .filter(id => {
        const ID_MAX_LEN = agentConfig.unstableIdMaxLen || 24
        
        if (agentConfig.unstableIdMaxLen) {
          log.warn("The value .env 'PINPOINT_UNSTABLE_ID_MAX_LEN' is not recommended.")
        }

        // ...
      })
  }
}
```

**Comment by feelform** [comment]
@nonoll 
it's a Pinpoint collector server restriction. so It can't apply a feature.

I'm so sorry. 

Have a good day ^^;
