### ISSUE TITLE
Inquery about supporting collector3.0v

### ISSUE THREAD

**Issue by KINX-ABH** [pinpoint-apm/pinpoint-node-agent#205]
Hello.

I'm currently configuring Pinpoint 3.0 version.

However, the 3.0 version is using the 3.0 version of collector.

I wonder if you have 3.0 version of collector support in node agent.

If you have, I wonder if you have a rough schedule.

Thank you

**Comment by feelform** [comment]
Hello, @KINX-ABH 

Do you have any problems with Pinpoint collector v3?

**Comment by feelform** [comment]
You can check https://github.com/pinpoint-apm/pinpoint-node-agent?tab=readme-ov-file#agent---collector-compatibility-table
