### ISSUE TITLE
Redis or mongodb is not displayed on the full link

### ISSUE THREAD

**Issue by wyfaq** [pinpoint-apm/pinpoint-node-agent#32]
Redis mongodb is not displayed on the full link, but the api  is called them.

**Comment by wyfaq** [comment]
pinpoint version: 2.2.0
node-agent:latest,v0.7.2

**Comment by feelform** [comment]
Hello @wyfaq 
Is it a problem only in v0.7.2 version?

**Comment by wyfaq** [comment]
> Hello @wyfaq
> Is it a problem only in v0.7.2 version?

just test v0.7.2
node.js v12

**Comment by feelform** [comment]
The Node agent supports Redis, ioredis(>=2.0.0 <5.0.0) and mysql core modules. 

Is there a sample app that can reproduce the redis module not showing up in the callstack?

**Comment by wyfaq** [comment]
thanks
