### ISSUE TITLE
http params (query string) not visible

### ISSUE THREAD

**Issue by jojoldu** [pinpoint-apm/pinpoint-node-agent#85]
Hi.
I'm testing several things to apply Pinpoint Node Agent to my company's project.
It wasn't a problem because I fully understood what some functions didn't do.

However, not seeing the request parameter is a big problem for me.
As with JVM monitoring, how do I see the request parameter at the pinpoint?
I would like to ask if a separate setting work is needed or if feature development is necessary.

**Expected Behavior**

![image](https://user-images.githubusercontent.com/7760496/118568854-a8907300-b7b3-11eb-8653-6dc4ecf2e817.png)

**Current Behavior**

![image](https://user-images.githubusercontent.com/7760496/118568878-b3e39e80-b7b3-11eb-94fc-1070d9241b10.png)

**Comment by feelform** [comment]
@jojoldu 
Thank you for your detail question. I am developing [call stack information likes JVM Pinpoint agent](https://github.com/pinpoint-apm/pinpoint-node-agent/issues/2). It will fix v0.9(next release version).

**Comment by jojoldu** [comment]
@feelform Thanks so much for the good news!
Is there a scheduled 0.9.0 release date?

**Comment by feelform** [comment]
@jojoldu 
It is scheduled to be released in August. Thanks

**Comment by feelform** [comment]
@jojoldu 
HTTP Param was resolved v0.9.0-next.0 
```
npm info pinpoint-node-agent

pinpoint-node-agent@0.8.2 | Apache-2.0 | deps: 10 | versions: 18
Pinpoint node agent provided by NAVER
https://github.com/pinpoint-apm/pinpoint-node-agent

keywords: pinpoint, log, logging, bug, bugs, error, errors, exception, exceptions, catch, monitor, monitoring, alert, alerts, performance, apm, ops, devops, stacktrace, trace, tracing, distributedtracing, distributed-tracing

dist
.tarball: https://registry.npmjs.org/pinpoint-node-agent/-/pinpoint-node-agent-0.8.2.tgz
.shasum: 7b75c8f12a6015c508914f0dc81d93273e369148
.integrity: sha512-g20Koeu7Z0YU+12X9QWQqSIQ1+HyU5Bo2R4JJJg0KwIHxzEl/vuuyQcEnq1CN+j/LgORCwZy+nGN7dP9Z7QTOw==
.unpackedSize: 684.2 kB

dependencies:
@grpc/grpc-js: ^1.2.3         google-protobuf: ^3.13.0      internal-ip: ^3.0.1           methods: ^1.1.2               semver: ^5.6.0                
end-of-stream: ^1.4.1         int64-buffer: ^0.99.1007      loglevel: ^1.6.1              require-in-the-middle: ^5.0.3 shimmer: ^1.2.0               

maintainers:
- feelform <feelform@gmail.com>
- npm.pinpoint.naver <npm.pinpoint.naver@gmail.com>

dist-tags:
latest: 0.8.2       next: 0.9.0-next.0  

published 2 weeks ago by feelform <feelform@gmail.com>
```

You can use `"pinpoint-node-agent": "0.9.0-next.0"` in package.json

**Comment by jojoldu** [comment]
@feelform 

Thank you very much!
I'll apply it and test it.

I think the pinpoint-node project is a very important project for nodejs developers.
I'm writing a basic tutorial post on pinpoint-node right now.
1) Installation 2) Basic functions 3) Application in the operation server etc..

Java developers know Pinpoint well, but
Node developers don't know well, so I want to promote this project a lot.

If any of my blog posts are written, I definitely want to contribute.

**Comment by jojoldu** [comment]
Wow! I tested it and it works!
thanks for the quick action.

![image](https://user-images.githubusercontent.com/7760496/120069962-92dc5100-c0c3-11eb-9493-16b55d1b5286.png)

**Comment by feelform** [comment]
@jojoldu 
Please write a tutorial in English and contribute. Thank you so much.

**Comment by jojoldu** [comment]
@feelform I wrote the Korean version of the tutorial.
I haven't written about a production server deployment yet.

If you take a look at the Korean version, I will change it to English and request a PR.

1. install: https://jojoldu.tistory.com/573
2. basic usage: https://jojoldu.tistory.com/576

**Comment by feelform** [comment]
@jojoldu 
The install, basic usage is too readable according to the flow. The code is also expected to be readable.

Please contribute your blog contents to English Markdown file  when your time is available. It is not urgent.

Have a nice day!
